import type { TopicMeta } from '#/content/types'
import {
  Lead,
  H2,
  P,
  TX,
  Callout,
  Bullets,
  Compare,
  Formula,
  MiniCheck,
} from '#/components/teach'

export const meta: TopicMeta = {
  id: 'counterfactual',
  num: 11,
  lecture: 'Lecture 11',
  title: 'Counterfactual Evaluation',
  blurb:
    'Estimating how a new policy would perform from biased logged data: off-policy evaluation and inverse propensity scoring.',
  minutes: 15,
  tags: ['off-policy', 'IPS', 'selection bias', 'propensity', 'logged data'],
  visualizers: [],
  examWeight: 'medium',
}

export function Content() {
  return (
    <div className="space-y-7">
      <Lead>
        We have logs of what users did — but only for the items the <em>old</em> system chose to
        show. Counterfactual evaluation asks: <TX>what would have happened if we had recommended
        differently?</TX>
      </Lead>

      <section className="space-y-3">
        <H2 id="problem">The problem with logged data</H2>
        <P>
          Logged interactions are generated by a <TX>logging policy</TX> (the system that was live
          when the data was collected). You only observe feedback for items that policy decided to
          show — a <TX>missing-not-at-random / selection bias</TX>.
        </P>
        <P>
          Naively scoring a new policy on this log is unfair: the new policy wants to show
          different items, and the log has little or no feedback for them. A standard offline
          metric silently rewards policies that agree with the old one.
        </P>
      </section>

      <section className="space-y-3">
        <H2 id="ope">Off-policy evaluation</H2>
        <P>
          <TX>Off-policy evaluation (OPE)</TX> estimates the performance of a{' '}
          <TX>target policy</TX> using data collected under a different <TX>logging policy</TX> —
          without deploying it. It lets you compare candidate recommenders from logs alone,
          avoiding slow and risky A/B tests.
        </P>
        <Compare
          a={{
            title: 'Model-based (direct method)',
            points: [
              'Fit a model that predicts the reward of any (context, action).',
              'Use it to score the target policy’s choices.',
              'Low variance, but biased if the reward model is wrong.',
            ],
          }}
          b={{
            title: 'Model-free (importance sampling)',
            points: [
              'Re-weight the logged rewards so the log looks like the target policy.',
              'Unbiased if propensities are known.',
              'High variance, especially when policies differ a lot.',
            ],
          }}
        />
      </section>

      <section className="space-y-3">
        <H2 id="ips">Inverse propensity scoring</H2>
        <P>
          The <TX>propensity</TX> is the probability the logging policy had of showing the item
          that was actually shown. IPS re-weights each logged reward by the inverse of that
          probability:
        </P>
        <Formula caption="IPS estimate of the target policy's value">
          V̂ = (1/n) Σ ( π<sub>target</sub>(a|x) / π<sub>log</sub>(a|x) ) · reward
        </Formula>
        <P>
          Rare actions (low logging probability) get up-weighted; over-shown actions get
          down-weighted. The estimate becomes <TX>unbiased</TX> — but a tiny propensity in the
          denominator can blow up, giving <TX>high variance</TX>. Remedies: clip / cap the weights,
          or use a <TX>doubly robust</TX> estimator that combines IPS with a reward model.
        </P>
      </section>

      <section className="space-y-3">
        <H2 id="issues">Other evaluation issues</H2>
        <Bullets
          items={[
            <>
              <TX>Position / presentation bias</TX> — items shown at the top get more clicks
              regardless of relevance.
            </>,
            <>
              <TX>Propensities must be known or estimated</TX> — impossible if the old system was
              deterministic (some exploration / randomisation is required).
            </>,
            <>
              <TX>Variance vs. bias trade-off</TX> — model-based is low-variance but biased;
              model-free is unbiased but high-variance.
            </>,
          ]}
        />
      </section>

      <Callout kind="exam">
        Key contrast to be able to state: counterfactual / off-policy evaluation reuses{' '}
        <TX>biased logged data</TX> to estimate a <em>new</em> policy, whereas an A/B test collects{' '}
        <TX>fresh unbiased data</TX> by actually deploying it. OPE is cheaper and safer; A/B is the
        gold standard for confirmation.
      </Callout>

      <MiniCheck q="Your old recommender was deterministic — it always showed its single top item. Why can't you do importance-sampling off-policy evaluation on its logs?">
        Importance sampling needs the <TX>propensity</TX> π<sub>log</sub>(a|x) — the probability
        the logging policy showed each action. A deterministic policy gives probability 1 to one
        item and 0 to all others, so any item the new policy would have shown has propensity 0 →
        division by zero. You need <TX>stochastic logging</TX> (some exploration / randomisation)
        for the propensities to be usable.
      </MiniCheck>
    </div>
  )
}
