/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DrillsRouteImport } from './routes/drills'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizersIndexRouteImport } from './routes/visualizers.index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as ExamIndexRouteImport } from './routes/exam.index'
import { Route as VisualizersVizIdRouteImport } from './routes/visualizers.$vizId'
import { Route as QuizTopicIdRouteImport } from './routes/quiz.$topicId'
import { Route as LearnTopicIdRouteImport } from './routes/learn.$topicId'
import { Route as ExamExamIdRouteImport } from './routes/exam.$examId'

const DrillsRoute = DrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizersIndexRoute = VisualizersIndexRouteImport.update({
  id: '/visualizers/',
  path: '/visualizers/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizersVizIdRoute = VisualizersVizIdRouteImport.update({
  id: '/visualizers/$vizId',
  path: '/visualizers/$vizId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTopicIdRoute = QuizTopicIdRouteImport.update({
  id: '/quiz/$topicId',
  path: '/quiz/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTopicIdRoute = LearnTopicIdRouteImport.update({
  id: '/learn/$topicId',
  path: '/learn/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamIdRoute = ExamExamIdRouteImport.update({
  id: '/exam/$examId',
  path: '/exam/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/drills': typeof DrillsRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
  '/quiz/$topicId': typeof QuizTopicIdRoute
  '/visualizers/$vizId': typeof VisualizersVizIdRoute
  '/exam/': typeof ExamIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/visualizers/': typeof VisualizersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/drills': typeof DrillsRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
  '/quiz/$topicId': typeof QuizTopicIdRoute
  '/visualizers/$vizId': typeof VisualizersVizIdRoute
  '/exam': typeof ExamIndexRoute
  '/learn': typeof LearnIndexRoute
  '/quiz': typeof QuizIndexRoute
  '/visualizers': typeof VisualizersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/drills': typeof DrillsRoute
  '/exam/$examId': typeof ExamExamIdRoute
  '/learn/$topicId': typeof LearnTopicIdRoute
  '/quiz/$topicId': typeof QuizTopicIdRoute
  '/visualizers/$vizId': typeof VisualizersVizIdRoute
  '/exam/': typeof ExamIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/quiz/': typeof QuizIndexRoute
  '/visualizers/': typeof VisualizersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cheatsheet'
    | '/drills'
    | '/exam/$examId'
    | '/learn/$topicId'
    | '/quiz/$topicId'
    | '/visualizers/$vizId'
    | '/exam/'
    | '/learn/'
    | '/quiz/'
    | '/visualizers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cheatsheet'
    | '/drills'
    | '/exam/$examId'
    | '/learn/$topicId'
    | '/quiz/$topicId'
    | '/visualizers/$vizId'
    | '/exam'
    | '/learn'
    | '/quiz'
    | '/visualizers'
  id:
    | '__root__'
    | '/'
    | '/cheatsheet'
    | '/drills'
    | '/exam/$examId'
    | '/learn/$topicId'
    | '/quiz/$topicId'
    | '/visualizers/$vizId'
    | '/exam/'
    | '/learn/'
    | '/quiz/'
    | '/visualizers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheatsheetRoute: typeof CheatsheetRoute
  DrillsRoute: typeof DrillsRoute
  ExamExamIdRoute: typeof ExamExamIdRoute
  LearnTopicIdRoute: typeof LearnTopicIdRoute
  QuizTopicIdRoute: typeof QuizTopicIdRoute
  VisualizersVizIdRoute: typeof VisualizersVizIdRoute
  ExamIndexRoute: typeof ExamIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  QuizIndexRoute: typeof QuizIndexRoute
  VisualizersIndexRoute: typeof VisualizersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/drills': {
      id: '/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof DrillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizers/': {
      id: '/visualizers/'
      path: '/visualizers'
      fullPath: '/visualizers/'
      preLoaderRoute: typeof VisualizersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizers/$vizId': {
      id: '/visualizers/$vizId'
      path: '/visualizers/$vizId'
      fullPath: '/visualizers/$vizId'
      preLoaderRoute: typeof VisualizersVizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$topicId': {
      id: '/quiz/$topicId'
      path: '/quiz/$topicId'
      fullPath: '/quiz/$topicId'
      preLoaderRoute: typeof QuizTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$topicId': {
      id: '/learn/$topicId'
      path: '/learn/$topicId'
      fullPath: '/learn/$topicId'
      preLoaderRoute: typeof LearnTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examId': {
      id: '/exam/$examId'
      path: '/exam/$examId'
      fullPath: '/exam/$examId'
      preLoaderRoute: typeof ExamExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheatsheetRoute: CheatsheetRoute,
  DrillsRoute: DrillsRoute,
  ExamExamIdRoute: ExamExamIdRoute,
  LearnTopicIdRoute: LearnTopicIdRoute,
  QuizTopicIdRoute: QuizTopicIdRoute,
  VisualizersVizIdRoute: VisualizersVizIdRoute,
  ExamIndexRoute: ExamIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  QuizIndexRoute: QuizIndexRoute,
  VisualizersIndexRoute: VisualizersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
